import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import Tabs from '@/components/Tabs/tabs'
import Tab, { Title, Content } from '@/components/Tabs/tab'
import LengthTab from "@/components/Tabs/specialized-tabs/LengthTab";
import WeightTab from "@/components/Tabs/specialized-tabs/WeightTab";
import TemperatureTab from "@/components/Tabs/specialized-tabs/TemperatureTab";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <h1>Unit Converter</h1>

        <Tabs>
          <LengthTab active={true} />
          <WeightTab />
          <TemperatureTab />
        </Tabs>

      </main>
    </>
  );
}
